sudo: false
language: node_js
node_js:
  - "node"
  - "8"
  - "6"
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm run lint
  - npm run test:ci
  - npm run coveralls
